version: '2'

networks:
  app-tier:
    driver: bridge

services:
  app:
    image: fulog:v1
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:docker@postgresql:5432/fulog?schema=public
    networks:
      - app-network
    ports:
      - '7777:8080'

  postgresql:
    image: 'bitnami/postgresql:latest'
    networks:
      - app-tier
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
