name: CI

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
      - run: npm run build

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: 'arn:aws:iam::307896280100:role/ecr-role'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build docker image
        id: build-docker-image
        env:
          REGISTRY: '${{ steps.login-ecr.outputs.registry }}'
          TAG: '${{ steps.generate_tag.outputs.sha }}'
          REPOSITORY: 'fulog-api-ci'
        run: |
          docker build -t $REGISTRY/fulog-api-ci:$TAG .
          docker push $REGISTRY/fulog-api-ci:$TAG
          IMAGE-$(echo $REGISTRY/fulog-api-ci:$TAG) 
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to app runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: fulog-api
          image: ${{ steps.build-docker-image.outputs.image}}
          access-role-arn: arn:aws:iam::307896280100:role/app-runner-role
          region: us-east-1
          cpu: 1
          memory: 2
          port: 3000
        # - uses: docker/login-action@v3
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push image
      #   run: docker push emanuellimamaia/fulog-backend:${{ steps.generate_tag.outputs.sha}}
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: emanuellimamaia/fulog-backend:${{ steps.generate_tag.outputs.sha }},emanuellimamaia/fulog-backend:latest
